### ISSUE TITLE
Prefix for Fastor definitions

### ISSUE THREAD

**Issue by dimbert** [romeric/Fastor#16] opened 2018-03-14 08:02 UTC
Could I suggest to prefix Fastor definition with `FASTOR_` to avoid conflicts with other libs? For example `Zero` or `One` defined in `commons.h` are pretty common. Moreover some of them are not used.

Thanks for this nice work !

**Comment by romeric** [comment] 2018-03-22 16:24
Thanks for your input. Ideally all definitions should have `FASTOR_` prefix. I would look into this very shortly.

**Comment by romeric** [comment] 2018-06-12 19:41
The issue is now fixed in 0769141. Many thanks for reporting.

**Closed by romeric** 2018-06-12 19:41 UTC
