### ISSUE TITLE
Why Tensor can't be constructed from vector

### ISSUE THREAD

**Issue by xiangzho72** [romeric/Fastor#106] opened 2020-06-24 18:15 UTC
Hi,

I'm trying the example in the wiki page but failed for compilation: 

std::array<double,4> std_array = {1,2,3,4};
Tensor<double,2,2> a(std_array); // construct a matrix from std::array

std::vector<double> std_vec = {1,2,3,4};
Tensor<double,2,2> a(std_vec); // construct a matrix from std::vector

Both above would fail.   Here is the error for construction from std_array: 
/home/sjt/kneron_sdk_prepostprocessor/external/include/Fastor/tensor/Tensor.h:87:19: note:   template argument deduction/substitution failed:
test.cpp:18:33: note:   ‘const std::array<double, 4>’ is not derived from ‘const Fastor::AbstractTensor<Derived, DIM>’
   Tensor<double,2,2> c(std_array); // construct a matrix from std::array
                                 ^
In file included from /home/sjt/kneron_sdk_prepostprocessor/external/include/Fastor/Fastor.h:19:0,
                 from test.cpp:1:
/home/sjt/kneron_sdk_prepostprocessor/external/include/Fastor/tensor/Tensor.h:67:19: note: candidate: Fastor::Tensor<T, Rest>::Tensor(const std::array<T, sizeof... (Rest)>&, int) [with T = double; long unsigned int ...Rest = {2, 2}]
     FASTOR_INLINE Tensor(const std::array<T,sizeof...(Rest)> &arr, int layout=RowMajor) {
                   ^~~~~~
/home/sjt/kneron_sdk_prepostprocessor/external/include/Fastor/tensor/Tensor.h:67:19: note:   no known conversion for argument 1 from ‘const std::array<double, 4>’ to ‘const std::array<double, 2>&’

Xiang

**Comment by romeric** [comment] 2020-06-26 11:54
Thanks for reporting. The issue is now fixed here aeec695. Please download a latest copy of Fastor.

**Closed by romeric** 2020-06-26 11:54 UTC
Labels: bug
