### ISSUE TITLE
Assignment to view does not work for complex<double>tensors

### ISSUE THREAD

**Issue by matejbadin** [romeric/Fastor#121] opened 2020-09-12 21:44 UTC
Hello Roman.

Maybe I'm dump or did not comprehend the idea of assignments to views, but
while these lines of code 
```
Tensor<double,2,2> A = {{0,1},{1,0}};
Tensor<double,4,4,2,2> B;
B.zeros();
B(0,3,all,all) = A;
```
lead to desired result - a construction of a tensor out of smaller blocks - e.g. having block B on the specified position of larger tensor A, things change if I use `complex<double>` tensors. Namely, with this code:
```
Tensor<complex<double>,2,2> A = {{(0,0),(1,0)},{(1,0),(0,0)}};
Tensor<complex<double>,4,4,2,2> B;
B(0,3,all,all) = A;
```
I am getting following error:
```
Fastor/expressions/views/tensor_views_nd.h(1657): error: no instance of overloaded function "Fastor::vector_setter" matches the argument list
            argument types are: (Fastor::SIMDVector<std::complex<double>, Fastor::simd_abi::sse>, std::complex<double> *, std::array<int, 2Ui64>)
              vector_setter(_vec,_expr.data(),inds);
```

I'm using the master-branch version of Fastor compiled with `Intel(R) C++ Intel(R) 64 Compiler, Version 19.1.1.216 Build 20200306`.

**Comment by romeric** [comment] 2020-09-13 13:12
Nope. You are not doing anything incorrect. This looks like a bug. I will have a look.

**Comment by romeric** [comment] 2020-09-13 14:23
The issue is now fixed  (here 096d0fc). Please download/clone the latest copy of Fastor.

You have an issue in your code though. Do not initialize std::complex tensors with initializer_lists with `{(a,b)}...`, be explicit `{std::complex(a,b)}...`:

~~~c++
using T = std::complex<double>;
Tensor<T,2,2> A = {{T(0,0),T(1,0)},{T(1,0),T(0,0)}};
Tensor<T,4,4,2,2> B;
B(0,3,all,all) = A;
~~~

**Closed by romeric** 2020-09-13 14:23 UTC

**Comment by matejbadin** [comment] 2020-09-13 14:27
Thanks!
