### ISSUE TITLE
compilation error for tensor-prod with g++-7 std=c++17

### ISSUE THREAD

**Issue by semoe** [romeric/Fastor#15] opened 2017-12-04 10:17 UTC
When trying to compile the following snippet with g++ 7.2.0, I receive the error:
`error: ambiguous template instantiation for struct Fastor::tensor_type_finder<Fastor::Tensor<double, 3> >`

snippet:
~~~c++
#include "Fastor.h"

using namespace Fastor;

int main(int argc, char *argv[]) {

    constexpr std::size_t N = 3;
    
    Tensor<double,N> vec1 = 0;
    Tensor<double,N> vec2 = 0;
    
    enum {a,b};
    
    Tensor<double,N,N> tensor_prod = einsum<Index<a>,Index<b>>(vec1,vec2);
    
    return 0;
}
~~~

Compiling the same snippet with the same compiler, but chosing std=c++14 gives no error.

**Comment by romeric** [comment] 2017-12-04 14:41
@semoe I am not able to reproduce this error with g++ 7.2.0 under linux or macOS. 
Can you specify your full compilation flags, please?

**Comment by romeric** [comment] 2017-12-04 16:02
My bad, I totally misread the title. I have now fixed this issue. Available immediately with a fresh clone of Fastor.

Thanks for reporting.

**Closed** 2017-12-15 01:01 UTC
Labels: bug
