### ISSUE TITLE
MSVC Compilation error in R0.6.1and R0.6

### ISSUE THREAD

**Issue by Yujie95** [romeric/Fastor#86] opened 2020-05-14 16:01 UTC
Hi Romeric,

Thanks for you excellent work! I am very interested in your library and I want to further use your library in my own project. However, I am using MSVC 2019 and there are errors during the building process. These errors only appear after R0.5.1. So, some changes after R0.5.1 broke the compilation. Could you please fix those problem. I would really appreciate that!

Thanks for you time and have a nice weekend.

**The error message are listed as follows:**
Severity | Code | Description | Project | File | Line | Suppression   State
-- | -- | -- | -- | -- | -- | --
Error | C2988 | unrecognizable   template declaration/definition | RidgeDetection | ...\Fastor-0.6.1\Fastor\backend\matmul\tmatmul.h | 69 |  
Error | C2059 | syntax   error: 'const' | RidgeDetection | ...\Fastor-0.6.1\Fastor\backend\matmul\tmatmul.h | 69 |  
Error | C2059 | syntax   error: ')' | RidgeDetection | ...\Fastor\backend\matmul\tmatmul.h | 69 |  
Error | C2143 | syntax   error: missing ';' before '{' | RidgeDetection | ...\Fastor-0.6.1\Fastor\backend\matmul\tmatmul.h | 69 |  
Error | C2447 | '{':   missing function header (old-style formal list?) | RidgeDetection | ...\Fastor-0.6.1\Fastor\backend\matmul\tmatmul.h | 69 |  
Error | C2988 | unrecognizable   template declaration/definition | RidgeDetection | ...\Fastor-0.6.1\Fastor\backend\matmul\tmatmul.h | 70 |  
Error | C2059 | syntax   error: 'const' | RidgeDetection | ...\Fastor-0.6.1\Fastor\backend\matmul\tmatmul.h | 70 |  
Error | C2059 | syntax   error: ')' | RidgeDetection | ...\Fastor-0.6.1\Fastor\backend\matmul\tmatmul.h | 70 |  
Error | C2143 | syntax   error: missing ';' before '{' | RidgeDetection | ...\Fastor-0.6.1\Fastor\backend\matmul\tmatmul.h | 70 |  
Error | C2447 | '{':   missing function header (old-style formal list?) | RidgeDetection | ...\Fastor-0.6.1\Fastor\backend\matmul\tmatmul.h | 70 |

**Comment by romeric** [comment] 2020-05-14 17:53
Thanks for reporting the issue. The issue is now fixed (0797cfa). It is available if you clone/download the latest version of Fastor. Let me know otherwise.

**Closed by romeric** 2020-05-14 17:53 UTC
