### ISSUE TITLE
Einsum not working with TensorMaps on const Data

### ISSUE THREAD

**Issue by matthiasneuner** [romeric/Fastor#113] opened 2020-07-24 11:02 UTC
Hello, 
this MWE does not compile for me on g++ (GCC) 10.1.0:

```
    using namespace Fastor;
    using i = Fastor::Index<0>;

    Tensor<double, 3> a         = {1.0, 2.0, 3.0};

    const double constData[]    = {1.0, 2.0, 3.0};
    TensorMap<const double, 3> b_FTMP ( constData);

    auto c = einsum < i, i > (a ,  b_FTMP);
```

Removing the const fixes the issue, but i guess that TensorMaps should also work with const data as intended above.
Thank you in advance and keep up the great work!

Compiler output:
```
In file included from /usr/include/c++/10.1.0/vector:67,
                 from /usr/local/include/Fastor/util/print.h:6,
                 from /usr/local/include/Fastor/util/util.h:5,
                 from /usr/local/include/Fastor/Fastor.h:16,
                 from /home/matthias/FastorLeviCivita/test.cpp:2:
/usr/include/c++/10.1.0/bits/stl_vector.h: In instantiation of ‘class std::vector<const double, std::allocator<const double> >’:
/usr/include/c++/10.1.0/type_traits:901:30:   required from ‘struct std::__is_constructible_impl<Fastor::Tensor<const double, 3>, const Fastor::Tensor<const double, 3>&>’
/usr/include/c++/10.1.0/type_traits:906:12:   required from ‘struct std::is_constructible<Fastor::Tensor<const double, 3>, const Fastor::Tensor<const double, 3>&>’
/usr/include/c++/10.1.0/type_traits:138:12:   required from ‘struct std::__and_<std::is_constructible<Fastor::Tensor<const double, 3>, const Fastor::Tensor<const double, 3>&>, std::is_convertible<const Fastor::Tensor<const double, 3>&, Fastor::Tensor<const double, 3> > >’
/usr/include/c++/10.1.0/tuple:471:7:   required from ‘static constexpr bool std::_TupleConstraints<<anonymous>, _Types>::__is_implicitly_constructible() [with _UTypes = {const Fastor::Tensor<const double, 3>&}; bool <anonymous> = true; _Types = {Fastor::Tensor<const double, 3>}]’
/usr/include/c++/10.1.0/tuple:538:65:   required by substitution of ‘template<bool _NotEmpty, typename std::enable_if<std::tuple<Fastor::Tensor<const double, 3> >::_TCC<_Cond>::__is_implicitly_constructible<const Tensor<const double, 3>&>(), bool>::type <anonymous> > constexpr std::tuple<Fastor::Tensor<const double, 3> >::tuple(const Fastor::Tensor<const double, 3>&) [with bool _NotEmpty = true; typename std::enable_if<std::tuple<Fastor::Tensor<const double, 3> >::_TCC<_Cond>::__is_implicitly_constructible<const Tensor<const double, 3>&>(), bool>::type <anonymous> = <missing>]’
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:163:91:   required from ‘decltype(auto) Fastor::internal::contraction_chain_evaluate(const AbstractTensorType0&, const AbstractTensorTypes& ...) [with AbstractTensorType0 = Fastor::TensorMap<const double, 3>; AbstractTensorTypes = {}]’
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:163:82:   required from ‘decltype(auto) Fastor::internal::contraction_chain_evaluate(const AbstractTensorType0&, const AbstractTensorTypes& ...) [with AbstractTensorType0 = Fastor::Tensor<double, 3>; AbstractTensorTypes = {Fastor::TensorMap<const double, 3>}]’
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:238:114:   required from ‘auto Fastor::einsum(const AbstractTensorType0&, const AbstractTensorType1&, const AbstractTensorTypes& ...) [with Index_I = Fastor::Index<0>; Index_J = Fastor::Index<0>; Index_Ks = {}; AbstractTensorType0 = Fastor::Tensor<double, 3>; AbstractTensorType1 = Fastor::TensorMap<const double, 3>; AbstractTensorTypes = {}]’
/home/matthias/FastorLeviCivita/test.cpp:106:42:   required from here
/usr/include/c++/10.1.0/bits/stl_vector.h:401:66: error: static assertion failed: std::vector must have a non-const, non-volatile value_type
  401 |       static_assert(is_same<typename remove_cv<_Tp>::type, _Tp>::value,
      |                                                                  ^~~~~
In file included from /usr/local/include/Fastor/tensor_algebra/einsum_explicit.h:10,
                 from /usr/local/include/Fastor/Fastor.h:26,
                 from /home/matthias/FastorLeviCivita/test.cpp:2:
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h: In instantiation of ‘auto Fastor::einsum(const AbstractTensorType0&, const AbstractTensorType1&, const AbstractTensorTypes& ...) [with Index_I = Fastor::Index<0>; Index_J = Fastor::Index<0>; Index_Ks = {}; AbstractTensorType0 = Fastor::Tensor<double, 3>; AbstractTensorType1 = Fastor::Tensor<const double, 3>; AbstractTensorTypes = {}]’:
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:192:52:   required from ‘static auto Fastor::internal::unpack_einsum_tuple<Index_I, Index_J, Index_Ks>::apply(Tuple, Fastor::std_ext::index_sequence<I ...>) [with Tuple = std::tuple<Fastor::Tensor<double, 3>, Fastor::Tensor<const double, 3> >; long unsigned int ...I = {0, 1}; Index_I = Fastor::Index<0>; Index_J = Fastor::Index<0>; Index_Ks = {}]’
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:198:21:   required from ‘static auto Fastor::internal::unpack_einsum_tuple<Index_I, Index_J, Index_Ks>::apply(Tuple) [with Tuple = std::tuple<Fastor::Tensor<double, 3>, Fastor::Tensor<const double, 3> >; Index_I = Fastor::Index<0>; Index_J = Fastor::Index<0>; Index_Ks = {}]’
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:238:77:   required from ‘auto Fastor::einsum(const AbstractTensorType0&, const AbstractTensorType1&, const AbstractTensorTypes& ...) [with Index_I = Fastor::Index<0>; Index_J = Fastor::Index<0>; Index_Ks = {}; AbstractTensorType0 = Fastor::Tensor<double, 3>; AbstractTensorType1 = Fastor::TensorMap<const double, 3>; AbstractTensorTypes = {}]’
/home/matthias/FastorLeviCivita/test.cpp:106:42:   required from here
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:238:77: error: use of ‘static auto Fastor::internal::unpack_einsum_tuple<Index_I, Index_J, Index_Ks>::apply(Tuple) [with Tuple = std::tuple<Fastor::Tensor<double, 3>, Fastor::Tensor<const double, 3> >; Index_I = Fastor::Index<0>; Index_J = Fastor::Index<0>; Index_Ks = {}]’ before deduction of ‘auto’
  238 |     return internal::unpack_einsum_tuple<Index_I,Index_J,Index_Ks...>::apply(internal::contraction_chain_evaluate(a,b,rest...));
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/Fastor/Fastor.h:19,
                 from /home/matthias/FastorLeviCivita/test.cpp:2:
/usr/local/include/Fastor/tensor/Tensor.h: In instantiation of ‘Fastor::Tensor<T, Rest>::Tensor(const Fastor::Tensor<T, Rest>&) [with T = const double; long unsigned int ...Rest = {3}]’:
/usr/include/c++/10.1.0/tuple:132:17:   required from ‘static auto Fastor::internal::unpack_einsum_tuple<Index_I, Index_J, Index_Ks>::apply(Tuple) [with Tuple = std::tuple<Fastor::Tensor<double, 3>, Fastor::Tensor<const double, 3> >; Index_I = Fastor::Index<0>; Index_J = Fastor::Index<0>; Index_Ks = {}]’
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:238:77:   required from ‘auto Fastor::einsum(const AbstractTensorType0&, const AbstractTensorType1&, const AbstractTensorTypes& ...) [with Index_I = Fastor::Index<0>; Index_J = Fastor::Index<0>; Index_Ks = {}; AbstractTensorType0 = Fastor::Tensor<double, 3>; AbstractTensorType1 = Fastor::TensorMap<const double, 3>; AbstractTensorTypes = {}]’
/home/matthias/FastorLeviCivita/test.cpp:106:42:   required from here
/usr/local/include/Fastor/tensor/Tensor.h:43:19: error: uninitialized const member in ‘const double [3]’ [-fpermissive]
   43 |     FASTOR_INLINE Tensor(const Tensor<T,Rest...> &other) {
      |                   ^~~~~~
In file included from /usr/local/include/Fastor/Fastor.h:19,
                 from /home/matthias/FastorLeviCivita/test.cpp:2:
/usr/local/include/Fastor/tensor/Tensor.h:181:20: note: ‘const double Fastor::Tensor<const double, 3>::_data [3]’ should be initialized
  181 |     FASTOR_ALIGN T _data[pack_prod<Rest...>::value];
      |                    ^~~~~
In file included from /usr/local/include/Fastor/Fastor.h:19,
                 from /home/matthias/FastorLeviCivita/test.cpp:2:
/usr/local/include/Fastor/tensor/Tensor.h: In instantiation of ‘Fastor::Tensor<T, Rest>::Tensor(const Fastor::AbstractTensor<Derived, DIMS>&) [with Derived = Fastor::TensorMap<const double, 3>; long unsigned int DIMS = 1; typename std::enable_if<((((! has_tensor_view_v<Derived>) && (! has_tensor_fixed_view_2d_v<Derived>)) && (! has_tensor_fixed_view_nd_v<Derived>)) || (DIMS != sizeof... (Rest))), bool>::type <anonymous> = false; T = const double; long unsigned int ...Rest = {3}]’:
/usr/local/include/Fastor/tensor/AbstractTensorFunctions.h:20:35:   required from ‘typename Derived::result_type Fastor::evaluate(const Fastor::AbstractTensor<Derived, DIM>&) [with Derived = Fastor::TensorMap<const double, 3>; long unsigned int DIMS = 1; typename Derived::result_type = Fastor::Tensor<const double, 3>]’
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:163:51:   required from ‘decltype(auto) Fastor::internal::contraction_chain_evaluate(const AbstractTensorType0&, const AbstractTensorTypes& ...) [with AbstractTensorType0 = Fastor::TensorMap<const double, 3>; AbstractTensorTypes = {}]’
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:163:82:   required from ‘decltype(auto) Fastor::internal::contraction_chain_evaluate(const AbstractTensorType0&, const AbstractTensorTypes& ...) [with AbstractTensorType0 = Fastor::Tensor<double, 3>; AbstractTensorTypes = {Fastor::TensorMap<const double, 3>}]’
/usr/local/include/Fastor/tensor_algebra/abstract_contraction.h:238:114:   required from ‘auto Fastor::einsum(const AbstractTensorType0&, const AbstractTensorType1&, const AbstractTensorTypes& ...) [with Index_I = Fastor::Index<0>; Index_J = Fastor::Index<0>; Index_Ks = {}; AbstractTensorType0 = Fastor::Tensor<double, 3>; AbstractTensorType1 = Fastor::TensorMap<const double, 3>; AbstractTensorTypes = {}]’
/home/matthias/FastorLeviCivita/test.cpp:106:42:   required from here
/usr/local/include/Fastor/tensor/Tensor.h:97:19: error: uninitialized const member in ‘const double [3]’ [-fpermissive]
   97 |     FASTOR_INLINE Tensor(const AbstractTensor<Derived,DIMS>& src) {
      |                   ^~~~~~
In file included from /usr/local/include/Fastor/Fastor.h:19,
                 from /home/matthias/FastorLeviCivita/test.cpp:2:
/usr/local/include/Fastor/tensor/Tensor.h:181:20: note: ‘const double Fastor::Tensor<const double, 3>::_data [3]’ should be initialized
  181 |     FASTOR_ALIGN T _data[pack_prod<Rest...>::value];
      |       
```             ^~~~~

**Comment by romeric** [comment] 2020-07-28 12:08
Thanks for reporting the issue. The issue is now fixed f6284e8. Your code should compile fine now. Please report if otherwise. Closing.

**Closed by romeric** 2020-07-28 12:08 UTC
Labels: bug
